"""Init migration

Revision ID: 93b679cc1542
Revises: 
Create Date: 2025-11-16 18:23:41.740342

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93b679cc1542'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_alembic',
    sa.Column('id', sa.Integer(), nullable=False, comment='ID записи'),
    sa.Column('name', sa.Text(), nullable=True, comment='Имя записи'),
    sa.PrimaryKeyConstraint('id'),
    schema='alembic_test_schema'
    )
    op.drop_table('test_table', schema='test_schema')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_table',
    sa.Column('test_table_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    schema='test_schema'
    )
    op.drop_table('test_alembic', schema='alembic_test_schema')
    # ### end Alembic commands ###
