"""add comments

Revision ID: f701a8dcbc9d
Revises: 93b679cc1542
Create Date: 2025-11-16 19:31:32.610634

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f701a8dcbc9d'
down_revision: Union[str, Sequence[str], None] = '93b679cc1542'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_alembic', sa.Column('display_name', sa.Text(), nullable=True, comment='Человекочитаемое имя колонки'), schema='alembic_test_schema')
    op.alter_column('test_alembic', 'name',
               existing_type=sa.TEXT(),
               comment='Техническое имя колонки',
               existing_comment='Имя записи',
               existing_nullable=True,
               schema='alembic_test_schema')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('test_alembic', 'name',
               existing_type=sa.TEXT(),
               comment='Имя записи',
               existing_comment='Техническое имя колонки',
               existing_nullable=True,
               schema='alembic_test_schema')
    op.drop_column('test_alembic', 'display_name', schema='alembic_test_schema')
    # ### end Alembic commands ###
